---
kind: pipeline
type: docker
name: verify
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/gn-agendapoint-service
    dry_run: true
    purge: true
trigger:
  event:
    - push
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/gn-agendapoint-service
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/gn-agendapoint-service
    dry_run: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/gn-agendapoint-service
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: jRjmiAlw0FYZvm/Exly3MzCVHhore8ft74F3zOPVTuTIFKD0LNm7ng==
---
kind: secret
name: docker_password
data: /njwYBU8FwWP7fi7cIYGSDQkjHFm2ZwaT0f2xpFbaQPhwHcGQLg/TbWiKFLwPFuqPaw1z5z9nUcC9jDrr/iFDg==
---
kind: signature
hmac: 28c18e02597b58bd7ecd0f91719e03770a0ac0911c1a4d3bbf9f4242b7485ab3

...
